### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by TygFF11** [TygFF11/furima-37250#26]
# URL　　
https://furima-37250.herokuapp.com/

# Basic認証のIDとパスワード　　
admin
2222

# 出品者用のメールアドレスとパスワード
test1@com　
aaa111

# 購入者用のメールアドレスとパスワード
test2@com　
aaa111

**Comment by wakazo228** [comment]
@TygFF11 さん、ご提出ありがとうございます！
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [x] **発送元の地域は、「---」と47都道府県の合計48項目が表示されるようにしましょう**
「岩手県」が不足しており、46都道府県、47項目しか表示されていません。

- [x] **発送までの日数は、「---、1\~2日で発送、2\~3日で発送、4\~7日で発送」の4項目が表示されるようにしましょう**
「---、1,2日で発送、2,3日で発送、4\~7日で発送」と表示されています。見本アプリと同様の形となるように修正しましょう。

- [x] **商品詳細画面では、商品出品時に登録した情報が、見本アプリと同様の形で出力されるようにしましょう**
商品説明部分に「商品説明」とのみ表示されており、登録した情報が表示されていません。

- [ ] **商品編集画面では、商品出品時とほぼ同じ見た目の商品情報編集ページが表示されるようにしましょう**
「カテゴリー」選択のドロップダウンに、下記画像の通り「配送料の負担」の項目が表示されています。
<img width="363" alt="スクリーンショット 2022-01-12 10 13 04" src="https://user-images.githubusercontent.com/53425908/149046667-129dbe88-7aa4-416d-a291-bbd97835b22a.png">


修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by TygFF11** [comment]
商品編集画面の内容以外は修正できました。
編集画面でカテゴリーが選ばれていない状態になっている問題について
localhost3000では選ばれた状態にあります。
https://i.gyazo.com/ae2d319aa087e2a5ea611097878ab441.png

git push heroku master　でherokuへpushしたので修正されてませんか？

**Comment by mo1015** [comment]
ご提出ありがとうございます！
動作の確認をしたところ、一部前回依頼箇所の修正が確認できませんでした。
マージやデプロイ忘れの可能性もございますので、再度以下のご確認をお願いします！

[修正依頼箇所]

- [x] **商品編集画面では、商品出品時とほぼ同じ見た目の商品情報編集ページが表示されるようにしましょう**
「カテゴリー」選択のドロップダウンに、「配送料の負担」の項目が表示されています。

※フォーム提出の前に必ず本番環境に反映できているか、今一度ご確認をお願いします。

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by TygFF11** [comment]
herokuで確認したところ、編集画面に情報が入力されていました。
何を修正すればいいでしょうか？
https://i.gyazo.com/2ad8af8070e3fc9d62221ec5b66101a4.mp4

**Comment by mo1015** [comment]
ご提出ありがとうございます！

[修正依頼箇所]

- [x] **商品編集画面では、商品出品時とほぼ同じ見た目の商品情報編集ページが表示されるようにしましょう**
**「カテゴリー」選択のドロップダウンに、「配送料の負担」の項目が表示**されています。
「カテゴリー」選択のドロップダウンにはカテゴリー項目を設定するようにしましょう。
<img width="672" alt="スクリーンショット_2022-01-12_11_55_34" src="https://user-images.githubusercontent.com/62644781/149055927-212c2498-aab3-4873-a5e7-29b6e3309251.png">



修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by TygFF11** [comment]
カテゴリーの順番と（レディース→メンズ）
カテゴリーの表示を修正しました。

**Comment by yusuketono** [comment]
@TygFF11 さん、フリマアプリ達成要件分の開発お疲れ様でした！
正常に動作することが確認できました！LGTMです！　
おめでとうございます🎉


**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願いいたします。**
**※Github上の最終課題の履歴はここまで頑張ってきた証です。削除せず大切に保管するようにしましょう。**

ここまで培ってきた知識や学びを活かして、これからは下記例のようなさらなる学習に取り組みましょう！

＜今後の学習例＞
・フリマアプリ追加実装
・オリジナルアプリ開発
・今まで学んできた言語あるいは新言語の学習　等
今後の学習方針や学習計画については、担当ライフコーチまでお気軽にご相談くださいませ。
また、以下提出物に関するリマインドです。

＜提出物＞
・最終課題説明文（フリマアプリ達成要件および、追加実装内容にて作成をお願いいたします）
・要件定義（追加実装あるいは、オリジナルアプリの内容で作成をお願いいたします）
※提出期日については、最終課題開始時に配布した下記動画にてご確認いただきますようお願いいたします。

＜最終課題に関する締め切りについての動画＞
https://master.tech-camp.in/v2/curriculums/7105

今後の流れに関して、もしご不明点がございましたら、
担当ライフコーチまでお気兼ねなくお申し付けくださいませ。


![最終課題終了_おめでとう画像1](https://user-images.githubusercontent.com/51428519/149059211-65876884-a0af-45a7-b11e-e2ee2e8a5c8e.png)

**Comment by TygFF11** [comment]
追加実装が終わりました。
確認してもらう必要はあるのでしょうか？

**Comment by chobi555** [comment]
レビュー依頼ありがとうございます。
追加実装につきましてはコードレビューは不要でございます。
以後、ご自身で内容を確認していただき、問題なければマージしていただくようお願い致します。

**Comment by TygFF11** [comment]
了解です。
